### ISSUE TITLE
QUESTION: что такое live-режим?

### ISSUE THREAD

**Issue by EvilBeaver** [akpaevj/OneSTools.EventLog#11]
Что такое упомянутый livе-режим?
Есть ли какая-то документация для пользователя nuget-библиотеки EventLog?

**Comment by akpaevj** [comment]
Документация написана уже на готовый инструмент, конкретно на библиотеку действительно не все расписано. В ближайшие пару дней актуализирую. Действие параметра описано только в комментарии к методу в коде) 
[https://github.com/akpaevj/OneSTools.EventLog/blob/master/OneSTools.EventLog/EventLogReader.cs](url) метод ReadNextEventLogItem. Там же реализована логика работы с параметром.

В обычном режиме работы метод возвращает null при достижении конца файла, а в LIVE режиме переходит в ожидание появления новых данных в файле и возвращает новую порцию только в этом случае (это блокирующий режим). Для наблюдения используется FileSystemWatcher на событиях Changed и Created
