### ISSUE TITLE
Invalid index name, must be lowercase

### ISSUE THREAD

**Issue by 1rV1N-git** [akpaevj/OneSTools.EventLog#12]
Спасибо большое за програмку!

При отправке в эластик необходимо приводить имя индекса к lowcase.

```
fail: OneSTools.EventLog.Exporter.Core.ElasticSearch.ElasticSearchStorage[0]
      Failed to index document 529 in onec-journal-BaseName-202101: Type: invalid_index_name_exception Reason: "Invalid index name [onec-journal-BaseName-202101], must be lowercase"
```

**Comment by akpaevj** [comment]
> Спасибо большое за програмку!
> 
> При отправке в эластик необходимо приводить имя индекса к lowcase.
> 
> ```
> fail: OneSTools.EventLog.Exporter.Core.ElasticSearch.ElasticSearchStorage[0]
>       Failed to index document 529 in onec-journal-BaseName-202101: Type: invalid_index_name_exception Reason: "Invalid index name [onec-journal-BaseName-202101], must be lowercase"
> ```

Есть такой нюанс, поправлю
