### ISSUE TITLE
Неправильная дата в логе.

### ISSUE THREAD

**Issue by 1rV1N-git** [akpaevj/OneSTools.EventLog#15]
Я думаю здесь ошибка вместо дня указан час. 

https://github.com/akpaevj/OneSTools.EventLog/blob/e3603bd0244f6654919ff10c122b53ab99e80f0c/OneSTools.EventLog.Exporter.Core/FileLogger.cs#L31

**Comment by akpaevj** [comment]
Да, это действительно ошибка
