### ISSUE TITLE
Ошибка при создании базы данных в ClickHouse

### ISSUE THREAD

**Issue by aknone** [akpaevj/OneSTools.EventLog#23]
Если в кластере 1С есть информационные базы c наименованием содержащих в себе символ "-" , то при создании базы по шаблону [IBNAME]_el в ClickHouse возникает ошибка создания базы. Т.к. наименование базы в ClickHouse не может содержать "-".

**Comment by akpaevj** [comment]
Согласно документации Elastic'а:
```
<index>
(Required, string) Name of the index you wish to create.

Index names must meet the following criteria:

- Lowercase only
- Cannot include \, /, *, ?, ", <, >, |, ` ` (space character), ,, #
- Indices prior to 7.0 could contain a colon (:), but that’s been deprecated and won’t be supported in 7.0+
- Cannot start with -, _, +
- Cannot be . or ..
- Cannot be longer than 255 bytes (note it is bytes, so multi-byte characters will count towards the 255 limit faster)
- Names starting with . are deprecated, except for hidden indices and internal indices managed by plugins
```
Обработка этих ограничений на текущий момент не рализована. Принято к исправлению

**Comment by akpaevj** [comment]
> Согласно документации Elastic'а:
> 
> ```
> <index>
> (Required, string) Name of the index you wish to create.
> 
> Index names must meet the following criteria:
> 
> - Lowercase only
> - Cannot include \, /, *, ?, ", <, >, |, ` ` (space character), ,, #
> - Indices prior to 7.0 could contain a colon (:), but that’s been deprecated and won’t be supported in 7.0+
> - Cannot start with -, _, +
> - Cannot be . or ..
> - Cannot be longer than 255 bytes (note it is bytes, so multi-byte characters will count towards the 255 limit faster)
> - Names starting with . are deprecated, except for hidden indices and internal indices managed by plugins
> ```
> 
> Обработка этих ограничений на текущий момент не рализована. Принято к исправлению

Вот так оно, с утра отвечать)) Для клика проверю ограничения. Так-же исправлю

**Comment by nixel2007** [comment]
@akpaevj Привет! Прости за пинг - удалось посмотреть на болячку?

**Comment by akpaevj** [comment]
Привет, пофиксил в dev ветке. Для обоих движков в наименованиях баз недопустимые символы будут заменяться на _
