### ISSUE TITLE
Ошибка при первоначальном создании db в Clickhouse

### ISSUE THREAD

**Issue by smochenov** [akpaevj/OneSTools.EventLog#31]
Добрый день
При первоначальном создании базы в CH возникает ошибка. Сама база создается, а вот таблиц в ней нет. 

> info: OneSTools.EventLog.Exporter.Core.EventLogExporter[0]
      Log folder: E:\1cv8\srvinfo\reg_1541\02eb2b3e-d9b0-46e4-bff6-059760ac586c\1Cv8Log
info: OneSTools.EventLog.Exporter.Core.EventLogExporter[0]
      Portion per request: 10000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\EventLogExporter
crit: OneSTools.EventLog.Exporter.EventLogExporterService[0]
      Failed to execute EventLogExporter
      ClickHouse.Client.ClickHouseServerException (0x0000003E): Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 154 (line 4, col 39): Codec(DoubleDelta, LZ4),
                          LgfEndPosition Int64 Codec(DoubleDelta, LZ4),
                          Id Int64 Codec(DoubleDelta, LZ4),
                  . Expected one of: token, ClosingRoundBracket, Comma, DEFAULT, MATERIALIZED, ALIAS, COMMENT, e.what() = DB::Exception

В логе вот это: 

> 2022-01-12 14:48:11.335 | Information | OneSTools.EventLog.Exporter.Core.EventLogExporter[0]
	Log folder: E:\1cv8\srvinfo\reg_1541\02eb2b3e-d9b0-46e4-bff6-059760ac586c\1Cv8Log
2022-01-12 14:48:11.337 | Information | OneSTools.EventLog.Exporter.Core.EventLogExporter[0]
	Portion per request: 10000
2022-01-12 14:48:11.464 | Information | Microsoft.Hosting.Lifetime[0]
	Application started. Press Ctrl+C to shut down.
2022-01-12 14:48:11.466 | Information | Microsoft.Hosting.Lifetime[0]
	Hosting environment: Production
2022-01-12 14:48:11.466 | Information | Microsoft.Hosting.Lifetime[0]
	Content root path: C:\EventLogExporter
2022-01-12 14:48:11.508 | Critical | OneSTools.EventLog.Exporter.EventLogExporterService[0]
	Failed to execute EventLogExporter

Подскажите, пожалуйста, что я делаю не так

**Comment by akpaevj** [comment]
Какая версия CH используется?

**Comment by smochenov** [comment]
Обновились до последней и все заработало, спасибо.
