### ISSUE TITLE
Ошибка импорта из баз, содержащих в имени "-"

### ISSUE THREAD

**Issue by milanse** [akpaevj/OneSTools.EventLog#33]
Если в имени базы содержатся минусы, не работает в режиме менеджера. Имя базы в кликхаусе не может содержать минусов ?

Failed to execute EventLogExporter
ClickHouse.Client.ClickHouseServerException (0x0000003E): Code: 62. DB::Exception: Syntax error: failed at position 33 ('-'): -base-test-kos_test. Expected one of: UUID, ON, storage definition, ENGINE, COMMENT, INTO OUTFILE, FORMAT, SETTINGS, end of query. (SYNTAX_ERROR) (version 21.12.3.32 (official build))

**Comment by akpaevj** [comment]
Да. Ошибка исправлена в репе #23, руки не дошли выложить сборку. В ближайшее время сделаю
