### ISSUE TITLE
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')

### ISSUE THREAD

**Issue by 1rV1N-git** [akpaevj/OneSTools.EventLog#45]
![image](https://user-images.githubusercontent.com/34376228/180171615-e76a8d30-127c-4bfe-bc00-9ef4d7538856.png)

**Comment by ShadowwMaks** [comment]
Приветсвую. Подскажите пожалуйста, не помните как с ошибкой справились?

**Comment by 1rV1N-git** [comment]
Добрый день.
Вроде удалил за пару дней выгруженных логов в Эластике что бы он заново их загрузил.
