### ISSUE TITLE
При прочтении логов возникает критическое исключение

### ISSUE THREAD

**Issue by dr-wut** [akpaevj/OneSTools.EventLog#5]
Добрый день
При запуске возникает такие логи:
dbug: Microsoft.Extensions.Hosting.Internal.Host[1]
      Hosting starting
info: OneSTools.EventLog.Exporter.Core.EventLogExporterService[0]
      Log folder: e:\test-log\log
info: OneSTools.EventLog.Exporter.Core.EventLogExporterService[0]
      Portion per request: 10000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: E:\test-log\EventLogExporterElasticSearch
dbug: Microsoft.Extensions.Hosting.Internal.Host[2]
      Hosting started
crit: OneSTools.EventLog.Exporter.Core.EventLogExporterService[0]
      Failed to execute EventLogExporter
      System.FormatException: Input string was not in a correct format.
         at OneSTools.EventLog.Exporter.Core.EventLogExporterService`1.ExecuteAsync(CancellationToken stoppingToken)

файл настроек:
{
  "Logging": {
    "LogLevel": {
      "Default": "0",
      "Microsoft": "0",
      "Microsoft.Hosting.Lifetime": "0"
    }
  },
  "ElasticSearch": {
    "Host": "http://172.*.*.131",
    "Port": 9200,
    "Index": "nazvanie",
    "Separation": "D" // H - hour, D - day, M - Month
  },
  "Exporter": {
    "LogFolder": "e:\\test-log\\log",
    "Portion": 10000
  }
}

**Comment by akpaevj** [comment]
Проблема уже исправлена, скоро загружу свежую версию

**Comment by akpaevj** [comment]
Исправлено, свежая версия зарелизена
