### ISSUE TITLE
Не заменяется поле events

### ISSUE THREAD

**Issue by dr-wut** [akpaevj/OneSTools.EventLog#6]
Добрый день
В кибане в разделе event все значения вида _$Job$_.Fail/_$Data$_.Update и так далее. Насколько я видел по коду там есть массив соотношения этих значений переведенным. Можно ли это поправить?
Заранее спасибо

**Comment by akpaevj** [comment]
Добрый. Эти значения как раз и получены из файла LGF. Судя по всему, 1С где-то внутри сама переводит названия вида "_$Data$_.Update" в "Данные.Изменение", т.е. ошибки в работе службы нет. То что вы просите - сделать можно, вручную описав соответствия и локализовав их. Сделаю в будущей версии

**Comment by akpaevj** [comment]
Сделано в версии 1.0.2
