### ISSUE TITLE
Возможность разбирать все базы сервера приложений

### ISSUE THREAD

**Issue by dr-wut** [akpaevj/OneSTools.EventLog#7]
Добрый день
Можно ли добавить следующий функционал - разбирать все базы сервера приложеений парся файл 1cv8wsrv.lst?
Я вижу это так:
1. в настройках указываем путь к файлу
2. дальше смотрим какие базы там есть
3. собираем пути к логам
4. льем все в еластик
Так же хотелось бы предусмотреть возможность включения или исключения этого функционала для баз по маске или конкретным списком

**Comment by akpaevj** [comment]
Парсинг файла списка ИБ сделать не проблема, но текущая архитектура выглядит как "1 служба - 1 папка лога". В описанном Вами сценарии надо делать либо отдельный менеджер служб сбора данных, либо реализовывать в пределах одной службы сбор с нескольких папок (но мне такой вариант не очень нравится). Подумаю над этой темой в будущих версиях

**Comment by akpaevj** [comment]
Реализован менеджер служб экспорта. Детальное описание инструмента и конфигурации в Readme
